"""real_initial

Revision ID: 97fd1a4cd401
Revises: 
Create Date: 2026-03-23 01:36:21.777283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '97fd1a4cd401'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('images',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('blob_url', sa.String(length=1024), nullable=False),
    sa.Column('blob_pathname', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embed_tasks',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('source_image_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('editguard_bits', sa.String(length=64), nullable=False),
    sa.Column('stegastamp_secret', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed'), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('result_image_url', sa.String(length=1024), nullable=True),
    sa.Column('stegastamp_image_url', sa.String(length=1024), nullable=True),
    sa.Column('residual_image_url', sa.String(length=1024), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_image_id'], ['images.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verify_logs',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('embed_task_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('stegastamp_found_codes', mysql.JSON(), nullable=True),
    sa.Column('editguard_recovered_bits', sa.String(length=64), nullable=True),
    sa.Column('editguard_accuracy', sa.String(length=20), nullable=True),
    sa.Column('mask_url', sa.String(length=1024), nullable=True),
    sa.Column('summary', mysql.JSON(), nullable=True),
    sa.Column('overall_pass', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['embed_task_id'], ['embed_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verify_logs')
    op.drop_table('embed_tasks')
    op.drop_table('images')
    op.drop_table('users')
    # ### end Alembic commands ###
